language: csharp
mono: none
dotnet: 2.1.300 
solution: Ninja.FileUtil.Core.sln
install:
  - dotnet restore
script:
 - dotnet build
 - dotnet test ./test/Ninja.FileUtil.Tests/Ninja.FileUtil.Tests.csproj
