//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ninja.FileUtil {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Ninja.FileUtil.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} failed to parse - Invalid enum value.
        /// </summary>
        internal static string InvalidEnumValueErrorFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidEnumValueErrorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid line format - number of column values do not match.
        /// </summary>
        internal static string InvalidLengthErrorFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidLengthErrorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid line format - is not delimeter separated.
        /// </summary>
        internal static string InvalidLineFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidLineFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid line format -  Invalid line type value.
        /// </summary>
        internal static string InvalidTypeValueError
        {
            get
            {
                return ResourceManager.GetString("InvalidTypeValueError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} failed to parse with error - {1}.
        /// </summary>
        internal static string LineExceptionFormat
        {
            get
            {
                return ResourceManager.GetString("LineExceptionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No column attributes found on Line  - {0}.
        /// </summary>
        internal static string NoColumnAttributesFoundFormat
        {
            get
            {
                return ResourceManager.GetString("NoColumnAttributesFoundFormat", resourceCulture);
            }
        }
    }
}
